version: "{branch} {build}"

build:
  verbosity: detailed

environment:
  SPRING_PROFILES_ACTIVE: windows
  matrix:
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
  - JAVA_HOME: C:\Program Files\Java\jdk9
  - JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0

matrix:
  fast_finish: true

build_script:
  - gradlew assemble --info --no-daemon

test_script:
  - gradlew check --info --no-daemon

on_success:
  - git status
  - ps: rm C:\Users\appveyor\.gradle\caches\modules-2\modules-2.lock -force
  - ps: rm C:\Users\appveyor\.gradle\caches\*\plugin-resolution\ -recurse -force

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper