version: "{branch} {build}"

build:
  verbosity: detailed

environment:
  SPRING_PROFILES_ACTIVE: windows


build_script:
  - gradlew test

on_success:
  - git status
  - ps: rm C:\Users\appveyor\.gradle\caches\modules-2\modules-2.lock -force
  - ps: rm C:\Users\appveyor\.gradle\caches\*\plugin-resolution\ -recurse -force

cache:
  - C:\Users\appveyor\.gradle\caches
  - C:\Users\appveyor\.gradle\wrapper