version: "{branch} {build}"

build:
  verbosity: detailed

environment:
  SPRING_PROFILES_ACTIVE: windows

cache:
  - '%USERPROFILE%/.gradle/caches/'
  - '%USERPROFILE%/.gradle/wrapper/'
build_script:
  - gradlew test
  